export const COPY = {
  nav: {
    home: 'Home',
    about: 'About Us',
    products: 'Products',
    cart: 'Cart',
    contact: 'Contact',
    publish: 'Publish',
  },
  cta: {
    addToCart: 'Add to Cart',
    orderNow: 'Order Now',
    viewCart: 'View Cart',
    checkout: 'Checkout',
    placeOrder: 'Place Order',
    continueShopping: 'Continue Shopping',
  },
  shipping: {
    available: 'International Shipping Available',
    weShipTo: 'We Ship To',
    countries: ['Germany', 'USA', 'UK', 'Dubai (UAE)', 'Malta'],
  },
  cart: {
    empty: 'Your cart is empty',
    subtotal: 'Subtotal',
    quantity: 'Quantity',
    remove: 'Remove',
  },
  checkout: {
    title: 'Checkout',
    customerDetails: 'Customer Details',
    orderSummary: 'Order Summary',
    name: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    country: 'Shipping Country',
    address: 'Shipping Address',
    notes: 'Order Notes (Optional)',
    success: 'Order Placed Successfully!',
    orderReference: 'Order Reference',
    thankYou: 'Thank you for your order. We will contact you shortly to confirm shipping details.',
  },
  contact: {
    title: 'Contact Us',
    whatsapp: 'Chat on WhatsApp',
    email: 'Email Us',
    phone: 'Call Us',
    followUs: 'Follow Us',
  },
  footer: {
    copyright: '© 2026. Built with',
    builtWith: 'using',
    love: '❤️',
  },
  publish: {
    title: 'Share Your Site',
    description: 'Share this link with anyone. No custom domain needed.',
    copyButton: 'Copy Link',
    copied: 'Copied',
    copiedSuccess: 'Link copied to clipboard!',
    copyError: 'Failed to copy link. Please try selecting and copying manually.',
    helperText: 'This link can be shared as-is. You don\'t need to set up a personal domain.',
    domainConstraints: 'Note: Custom domains must be 5-50 characters and contain only letters, numbers, and hyphens.',
  },
};
