/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customer' : IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  }),
  'totalAmountCents' : IDL.Nat,
  'placedAt' : IDL.Int,
  'products' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Category = IDL.Variant({
  'oil' : IDL.Null,
  'blends' : IDL.Null,
  'spices' : IDL.Null,
  'sweets' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([Order], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customer' : IDL.Record({
      'country' : IDL.Text,
      'name' : IDL.Text,
      'email' : IDL.Text,
      'address' : IDL.Text,
      'notes' : IDL.Opt(IDL.Text),
      'phone' : IDL.Text,
    }),
    'totalAmountCents' : IDL.Nat,
    'placedAt' : IDL.Int,
    'products' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const Category = IDL.Variant({
    'oil' : IDL.Null,
    'blends' : IDL.Null,
    'spices' : IDL.Null,
    'sweets' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceCents' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([Order], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };